/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import org.bson.Document;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.UUID;

public class App {

  // Helper method to read file content as a single string
  public static String readFileAsString(String filePath) throws IOException {
    StringBuilder contentBuilder = new StringBuilder();
    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
      String line;
      while ((line = br.readLine()) != null) {
        contentBuilder.append(line);
      }
    }
    return contentBuilder.toString();
  }

  public static void main(String[] args) {
    MongoClient mongoClient = MongoClients
        .create("mongodb://localhost:27017,localhost:27018,localhost:27019?replicaSet=replset");

    BSONDocumentHandler handler = new BSONDocumentHandler(
        mongoClient,
        "test");
    UUID id = UUID.randomUUID();

    String filePath = "/Users/carloscastro/Downloads/30MB_JSON.json";
    try {

      // Read JSON content from the file
      String jsonContent = readFileAsString(filePath);

      // Convert the JSON content to a BSON Document
      Document document = Document.parse(jsonContent);
      // System.out.println("Document loaded: " + document.toJson());

      handler.saveDocument(
          id,
          document,
          "test");

      Document doc = handler.readDocument(id, "test");
      System.out.println(doc.toString());
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}
